#!/bin/sh

SKETCHTOOL=/Applications/Sketch.app/Contents/Resources/sketchtool/bin/sketchtool
DIR_PATH=$PWD
SKETCH_FILE=(*.sketch)
FILE_PATH=$DIR_PATH/$SKETCH_FILE
EXPORT_FOLDER=$DIR_PATH/assets
BLUE='\033[1;36m'
NC='\033[0m'

echo "${BLUE}Deleting old artboard examples 🗑${NC}"
rm -rf $EXPORT_FOLDER/*
echo "${BLUE}Exporting current artboards 🎨${NC}"
$SKETCHTOOL export artboards $FILE_PATH --output=$EXPORT_FOLDER --formats=png --include-symbols=NO
git add assets/
echo "${BLUE}Artboards exported and staged to commit👏${NC}"
